server:
  port: 8206

spring:
  application:
    name: xiaoyu-module-workflow
  profiles:
    active: dev
  config:
    import: nacos:application-${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        group: DEFAULT_GROUP
        file-extension: yml
      discovery:
        group: DEFAULT_GROUP


# Knife4j
knife4j:
  enable: true

# Management
management:
  endpoints:
    web:
      exposure:
        include: '*'