server:
  port: 8201

spring:
  application:
    name: xiaoyu-module-system
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      config:
        group: DEFAULT_GROUP
        file-extension: yml
      discovery:
        group: DEFAULT_GROUP
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

# MyBatis-Flex
mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Management
management:
  endpoints:
    web:
      exposure:
        include: '*'